const safeTagsAndAttributes = {
    a: [
        "target",
        "href",
        "title",
        "data-collection-id",
        "data-page-id",
        "rel",
        "data-user-id", 
        "data-user-id-old"
    ],
    abbr: ["title"],
    address: [],
    area: ["shape", "coords", "href", "alt"],
    article: [],
    aside: [],
    audio: ["autoplay", "controls", "loop", "preload", "src"],
    b: [],
    bdi: ["dir"],
    bdo: ["dir"],
    big: [],
    blockquote: ["cite"],
    br: [],
    caption: [],
    center: [],
    cite: [],
    code: [],
    col: ["align", "valign", "span", "width"],
    colgroup: ["align", "valign", "span", "width"],
    dd: [],
    del: ["datetime"],
    details: ["open"],
    div: ["style"],
    dl: [],
    dt: [],
    em: [],
    font: ["color", "size", "face", "style"],
    footer: [],
    h1: ["style"],
    h2: ["style"],
    h3: ["style"],
    h4: ["style"],
    h5: ["style"],
    h6: ["style"],
    header: ["style"],
    hr: ["style", "class"],
    i: [],
    img: ["src", "alt", "title", "width", "height", "style", "class"],
    ins: ["datetime"],
    li: ["style"],
    mark: [],
    nav: [],
    ol: ["style"],
    p: ["style"],
    pre: ["style"],
    s: [],
    section: [],
    small: [],
    span: ["style", "class"],
    sub: [],
    sup: [],
    strong: [],
    table: ["width", "border", "align", "valign", "style", "class"],
    tbody: ["align", "valign", "style", "class"],
    td: [
        "width",
        "rowspan",
        "colspan",
        "align",
        "valign",
        "style",
        "class"
    ],
    tfoot: ["align", "valign", "style", "class"],
    th: [
        "width",
        "rowspan",
        "colspan",
        "align",
        "valign",
        "style",
        "class"
    ],
    thead: ["align", "valign", "style", "class"],
    tr: ["rowspan", "align", "valign", "style", "class"],
    tt: [],
    u: [],
    ul: ["style", "class"],
    video: [
        "style",
        "autoplay",
        "controls",
        "loop",
        "preload",
        "src",
        "height",
        "width"
    ],
    iframe: [
        "src",
        "frameborder",
        "allow",
        "sandbox",
        "referrerpolicy",
        "allowfullscreen",
        "style",
        "class"
    ]
};


export {
  safeTagsAndAttributes
};