name: CI

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: eu.gcr.io/spacegapps/frontend-tools:2.0.0
      - name: Build & deploy
        run: |
          setup-npm
          lerna bootstrap
          yarn run build:docs
          yarn run docs:deploy
